apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc
  project: default
  source:
    path: proxmoxcsi
    repoURL: https://github.com/VerticalVeith/homelab
    targetRevision: HEAD
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
