apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vintage-story-data
  namespace: vintage-story
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-data
