apiVersion: v1
kind: Service
metadata:
  name: vintage-story
  namespace: vintage-story
  labels:
    app: vintage-story
spec:
  ports:
    - port: 42420
      targetPort: 42420
      protocol: TCP
      name: tcp
    - port: 42420
      targetPort: 42420
      protocol: UDP
      name: udp
  selector:
    app: vintage-story
