apiVersion: v1
kind: Service
metadata:
  name: homeassistant-vm
  namespace: home-assistant
spec:
  type: ExternalName
  externalName: 192.168.12.250
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: home-assistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.buergerhoff.com`)
      kind: Rule
      services:
        - name: homeassistant-vm
          port: 8123
  tls:
    certResolver: main